[2019-12-28 03:41:33] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "$opsLimit must be 3 or greater." at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php line 40 {"exception":"[object] (InvalidArgumentException(code: 0): $opsLimit must be 3 or greater. at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php:40)"} []
[2019-12-28 03:51:09] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "$opsLimit must be 3 or greater." at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php line 40 {"exception":"[object] (InvalidArgumentException(code: 0): $opsLimit must be 3 or greater. at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php:40)"} []
[2019-12-28 03:52:38] php.CRITICAL: Uncaught Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 03:52:38] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line" at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php line 0 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 03:53:51] php.CRITICAL: Uncaught Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 03:53:52] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line" at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php line 0 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 03:55:30] php.CRITICAL: Uncaught Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 03:55:30] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line" at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php line 0 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 03:55:48] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "$opsLimit must be 3 or greater." at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php line 40 {"exception":"[object] (InvalidArgumentException(code: 0): $opsLimit must be 3 or greater. at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php:40)"} []
[2019-12-28 03:56:09] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "$opsLimit must be 3 or greater." at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php line 40 {"exception":"[object] (InvalidArgumentException(code: 0): $opsLimit must be 3 or greater. at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php:40)"} []
[2019-12-28 03:56:24] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "$opsLimit must be 3 or greater." at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php line 40 {"exception":"[object] (InvalidArgumentException(code: 0): $opsLimit must be 3 or greater. at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php:40)"} []
[2019-12-28 03:56:40] php.CRITICAL: Uncaught Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 03:56:40] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line" at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php line 0 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 03:57:33] php.CRITICAL: Uncaught Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 03:57:33] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line" at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php line 0 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 04:06:08] php.CRITICAL: Uncaught Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 04:06:08] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line" at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php line 0 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 04:11:07] php.CRITICAL: Uncaught Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 04:11:07] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line" at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php line 0 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 04:14:50] php.CRITICAL: Uncaught Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 04:14:50] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line" at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php line 0 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php:0)"} []
[2019-12-28 04:18:15] php.CRITICAL: Uncaught Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at xdebug://debug-eval(1) : eval()'d code:0)"} []
[2019-12-28 04:18:16] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Method Trikoder\Bundle\OAuth2Bundle\League\Entity\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line" at xdebug://debug-eval(1) : eval()'d code line 0 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Method Trikoder\\Bundle\\OAuth2Bundle\\League\\Entity\\AccessToken::__toString() must not throw an exception, caught InvalidArgumentException: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at xdebug://debug-eval(1) : eval()'d code:0)"} []
[2019-12-28 04:25:34] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "$opsLimit must be 3 or greater." at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php line 40 {"exception":"[object] (InvalidArgumentException(code: 0): $opsLimit must be 3 or greater. at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php:40)"} []
[2019-12-28 04:55:03] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "$opsLimit must be 3 or greater." at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php line 40 {"exception":"[object] (InvalidArgumentException(code: 0): $opsLimit must be 3 or greater. at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php:40)"} []
[2019-12-28 04:57:15] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "$opsLimit must be 3 or greater." at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php line 40 {"exception":"[object] (InvalidArgumentException(code: 0): $opsLimit must be 3 or greater. at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php:40)"} []
[2019-12-28 04:57:28] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "$opsLimit must be 3 or greater." at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php line 40 {"exception":"[object] (InvalidArgumentException(code: 0): $opsLimit must be 3 or greater. at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php:40)"} []
[2019-12-28 04:57:51] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line" at /var/www/symfony/vendor/lcobucci/jwt/src/Signer/OpenSSL.php line 90 {"exception":"[object] (InvalidArgumentException(code: 0): It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/lcobucci/jwt/src/Signer/OpenSSL.php:90)"} []
[2019-12-28 04:58:44] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line" at /var/www/symfony/vendor/lcobucci/jwt/src/Signer/OpenSSL.php line 90 {"exception":"[object] (InvalidArgumentException(code: 0): It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/lcobucci/jwt/src/Signer/OpenSSL.php:90)"} []
[2019-12-28 04:59:42] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line" at /var/www/symfony/vendor/lcobucci/jwt/src/Signer/OpenSSL.php line 90 {"exception":"[object] (InvalidArgumentException(code: 0): It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line at /var/www/symfony/vendor/lcobucci/jwt/src/Signer/OpenSSL.php:90)"} []
[2019-12-28 05:02:34] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "$opsLimit must be 3 or greater." at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php line 40 {"exception":"[object] (InvalidArgumentException(code: 0): $opsLimit must be 3 or greater. at /var/www/symfony/vendor/symfony/security-core/Encoder/NativePasswordEncoder.php:40)"} []
[2019-12-28 05:10:16] console.ERROR: Error thrown while running command "doctrine:schema:create". Message: "Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE security_and_acl_user (id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)', play_head INT NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME NOT NULL, roles JSON NOT NULL, password LONGTEXT NOT NULL, active TINYINT(1) NOT NULL, user_name_value VARCHAR(64) NOT NULL, user_type LONGTEXT NOT NULL, is_blocked TINYINT(1) DEFAULT '0' NOT NULL, block_date DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_4A4FE7317436CC9D (user_name_value), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'security_and_acl_user' already exists' while executing DDL: CREATE TABLE security_and_acl_user (id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)', play_head INT NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME NOT NULL, roles JSON NOT NULL, password LONGTEXT NOT NULL, active TINYINT(1) NOT NULL, user_name_value VARCHAR(64) NOT NULL, user_type LONGTEXT NOT NULL, is_blocked TINYINT(1) DEFAULT '0' NOT NULL, block_date DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_4A4FE7317436CC9D (user_name_value), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB" {"exception":"[object] (Doctrine\\ORM\\Tools\\ToolsException(code: 0): Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE security_and_acl_user (id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)', play_head INT NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME NOT NULL, roles JSON NOT NULL, password LONGTEXT NOT NULL, active TINYINT(1) NOT NULL, user_name_value VARCHAR(64) NOT NULL, user_type LONGTEXT NOT NULL, is_blocked TINYINT(1) DEFAULT '0' NOT NULL, block_date DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_4A4FE7317436CC9D (user_name_value), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'security_and_acl_user' already exists' while executing DDL: CREATE TABLE security_and_acl_user (id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)', play_head INT NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME NOT NULL, roles JSON NOT NULL, password LONGTEXT NOT NULL, active TINYINT(1) NOT NULL, user_name_value VARCHAR(64) NOT NULL, user_type LONGTEXT NOT NULL, is_blocked TINYINT(1) DEFAULT '0' NOT NULL, block_date DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_4A4FE7317436CC9D (user_name_value), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB at /var/www/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/ToolsException.php:34, Doctrine\\DBAL\\Exception\\TableExistsException(code: 0): An exception occurred while executing 'CREATE TABLE security_and_acl_user (id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)', play_head INT NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME NOT NULL, roles JSON NOT NULL, password LONGTEXT NOT NULL, active TINYINT(1) NOT NULL, user_name_value VARCHAR(64) NOT NULL, user_type LONGTEXT NOT NULL, is_blocked TINYINT(1) DEFAULT '0' NOT NULL, block_date DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_4A4FE7317436CC9D (user_name_value), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'security_and_acl_user' already exists at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:38, Doctrine\\DBAL\\Driver\\PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'security_and_acl_user' already exists at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80, PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'security_and_acl_user' already exists at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:75)","command":"doctrine:schema:create","message":"Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE security_and_acl_user (id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)', play_head INT NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME NOT NULL, roles JSON NOT NULL, password LONGTEXT NOT NULL, active TINYINT(1) NOT NULL, user_name_value VARCHAR(64) NOT NULL, user_type LONGTEXT NOT NULL, is_blocked TINYINT(1) DEFAULT '0' NOT NULL, block_date DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_4A4FE7317436CC9D (user_name_value), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'security_and_acl_user' already exists' while executing DDL: CREATE TABLE security_and_acl_user (id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)', play_head INT NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME NOT NULL, roles JSON NOT NULL, password LONGTEXT NOT NULL, active TINYINT(1) NOT NULL, user_name_value VARCHAR(64) NOT NULL, user_type LONGTEXT NOT NULL, is_blocked TINYINT(1) DEFAULT '0' NOT NULL, block_date DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_4A4FE7317436CC9D (user_name_value), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB"} []
[2019-12-28 05:10:17] console.ERROR: Error thrown while running command "auditor_framework:security-and-acl:create-initial-users". Message: "The EntityManager is closed." {"exception":"[object] (TheCodeFighters\\Bundle\\AuditorFramework\\Common\\Types\\Application\\Exception\\TransactionalApplicationException(code: 0): The EntityManager is closed. at /var/www/symfony/vendor/oscarlopez1616/auditor-framework/src/Common/Module/SecurityAndAcl/Application/Command/CreateUser/CreateUserService.php:59)","command":"auditor_framework:security-and-acl:create-initial-users","message":"The EntityManager is closed."} []
